# Generated by Django 4.2.13 on 2024-06-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_year', models.CharField(max_length=4)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rejection_percentage', models.CharField(max_length=10)),
                ('reason_1', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_2', models.CharField(blank=True, max_length=255, null=True)),
                ('reason_3', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
